[zuul] Add graphing Job
infrawatch/feature-verification-tests pull request #134
Opened 2024-07-29 07:06 UTC by mgirgisf

2024-09-10 08:13 UTC, mgirgisf commented
recheck

2024-09-17 18:35 UTC, elfiesmelfie requested changes

2024-09-17 18:35 UTC, elfiesmelfie commented on roles/telemetry_graphing/handlers/main.yml
You can remove the handlers dir if it's not used

2024-09-17 18:35 UTC, elfiesmelfie commented on roles/telemetry_graphing/README.md
> +BSD
Should be apache 2

2024-09-17 18:35 UTC, elfiesmelfie commented on roles/telemetry_graphing/README.md
> +A brief description of the role goes here.
Please update this README to add a description of the role, the requirements, vars, etc

2024-09-17 18:35 UTC, elfiesmelfie commented on roles/telemetry_graphing/vars/main.yml
Remove this if it's not used

2024-09-17 18:35 UTC, elfiesmelfie commented on ci/run_graphing_test.yml
> +
The typical approach is to use "ignore_errors: true" so that all the tests get run, then the report_result will check for failures.

2024-09-17 18:35 UTC, elfiesmelfie commented on roles/telemetry_graphing/tasks/main.yml
> +- name: "[Test] verify promotheus query"
I think that this will always pass as long as the file is successfully included.

2024-09-17 18:35 UTC, elfiesmelfie commented on roles/telemetry_graphing/tasks/main.yml
> +- name: "[Test] verify promotheus query"
So the test should be in one of the tasks in the included file

2024-09-27 08:26 UTC, closed without merging