[logging] Add projects test
infrawatch/feature-verification-tests pull request #162
Opened 2024-10-16 07:27 UTC by mgirgisf

2024-10-17 09:18 UTC, vyzigold approved these changes

2024-10-17 12:34 UTC, ayefimov-1 commented on roles/common/tasks/project_tests.yml
These tests are common tests and should *not* refer to any specific functions or features.

Recommend name change:
- name: Verify projects "{{ item }}"

2024-10-17 12:48 UTC, ayefimov-1 requested changes
Some of the changes made defeat the purpose of having a "common" role for telemetry testing.  Common role plays, tasks and playbooks should be reusable and feature agnostic.

2024-10-18 07:47 UTC, mgirgisf commented on roles/common/tasks/main.yml
The aim of using a main.yml is to provide a single entrypoint to the role, which will select the tests based on the defined variables. its the same way we use in pod-tests

2024-10-18 12:35 UTC, ayefimov-1 approved these changes
Thank you. Looks good.

2024-10-18 13:06 UTC, merged