Adding polarion TC IDs for graphing.
infrawatch/feature-verification-tests pull request #182
Opened 2024-11-28 10:05 UTC by lnatapov

Adding polarion TC IDs for graphing.

2024-11-28 12:25 UTC, mgirgisf commented on roles/telemetry_graphing/tasks/verify_url.yml
> +    TEST UI-1 Check OpenShift Console URL is accessible
```suggestion
    TEST Check OpenShift Console URL is accessible
```

2024-11-28 15:58 UTC, elfiesmelfie approved these changes

2024-11-28 16:46 UTC, elfiesmelfie requested changes

2024-11-28 17:27 UTC, elfiesmelfie approved these changes

2024-11-28 17:27 UTC, elfiesmelfie commented on roles/telemetry_graphing/tasks/cypress_test.yml
> +- name: |
This is not related to your change, and I have taken note that a follow-up is needed

2024-12-03 17:51 UTC, elfiesmelfie approved these changes

2024-12-04 07:40 UTC, mgirgisf approved these changes

2024-12-05 19:48 UTC, merged